evmos/ethermint

app/ante/ante.go
app/ante/eth.go
app/ante/utils_test.go
crypto/ethsecp256k1/ethsecp256k1.go
ethereum/rpc/eth_api.go
ethereum/rpc/types/types.go
go.mod
go.sum
tests/signer.go
x/evm/handler_test.go
x/evm/types/msg.go
x/evm/types/msg_test.go
x/evm/types/utils.go

Closes: #XXX
Enable `eth_sendTransaction` and `eth_sign` rpc endpoints without passing the private key to the JSON-RPC service and relying solely on the keyring.
______
______
For admin use:

rpc, evm: secure tx signing

---

CHANGELOG.md
go.mod
go.sum
x/evm/keeper/abci.go
x/evm/keeper/msg_server.go
x/evm/types/events.go
x/evm/types/msg.go
x/evm/types/state_transition.go

Closes: #XXX
______
______
For admin use:

evm: SDK metrics

---

client/keys.go

Closes: #40
Cosmos SDK update from 0.42.4 to 0.42.5 broke the key.go `runAddCmd` methods as the signature for `RunAddCmd` from Cosmos SDK changed with the upgrade.
This PR provides a fix
______
______
For admin use:

fix runAddCmd after cosmos sdk update from  0.42.4 to 0.42.5

---

CHANGELOG.md
ethereum/rpc/types/utils.go

Use `EmptyUncleHash` and `EmptyRootHash` instead of the zero `Hash` value
______
______
For admin use:

rpc: fix empty root and uncle hash

---

app/ante/ante_test.go
app/ante/eth_test.go
app/ante/utils_test.go
ethereum/rpc/eth_api.go
tests/importer/importer_test.go
x/evm/handler_test.go
x/evm/types/msg.go
x/evm/types/msg_test.go

fixes signature verification by leveraging the Signer interface from geth. Currently only supports EIP2929 signer (no legacy txs)

evm: fix sig verification

---

ethereum/rpc/eth_api.go

Closes: #99
Fix the build error introduced in #84 
```
ethereum/rpc/eth_api.go:954:39: cannot use res.CodeHash (type string) as type []byte in argument to common.BytesToHash
make: *** [build] Error 2
```
______
______
For admin use:

Fix CodeHash type error on build

---

CHANGELOG.md
app/ante/eth.go
app/ante/eth_test.go
x/evm/types/msg.go
x/evm/types/msg_test.go
x/evm/types/tx_data.go
x/evm/types/tx_data_test.go

evm: support legacy tx

---

ethereum/rpc/personal.go

`personal_unlockAccount` now doesn't return an error.

rpc: remove error on `personal_unlockAccount`

---

app/ante/ante.go
app/ante/ante_test.go
app/ante/eth.go
app/ante/utils_test.go
ethereum/rpc/eth_api.go

fixes #118
Although my test still don't success for errors related to gas, but this change do pass the signature validation issue.
Eth transactions have signature inside the message, so it's ok to not sign at cosmos tx level.
______
______
For admin use:

ignore no signature error for evm transactions

---

CHANGELOG.md
docs/basics/json_rpc.md
ethereum/rpc/apis.go
ethereum/rpc/backend.go
ethereum/rpc/txpool_api.go

Closes: #124 
Enabled txpool namespace with `txpool_content` method that complies with the go ethereum [documentation](https://geth.ethereum.org/docs/rpc/ns-txpool). The decision was to return an empty response (this is explained in further detail in the issue). Endpoint is needed to unblock block explorer integration
NOTE: Did not update documentation as the method is not fully functional yet. Happy to do it if it is required. 
______
______
For admin use:

feat: add txpool namespace RPC methods

---

ethereum/rpc/types/utils.go

Closes: #148 
Small change to return a valid 16bit default nonce value on RPC method `eth_getBlockByNumber` . More info in the issue.
______
______
For admin use:

evm: return valid nonce on `eth_getBlockByNumber`

---

ethereum/rpc/namespaces/eth/api.go
ethereum/rpc/types/types.go

Closes: #XXX
when Args are nils, it triggers nil pointer exception.
This PR brings a fix
______
______
For admin use:

fix nil pointer exception when parameters are nil

---

CHANGELOG.md
app/app.go
ethereum/rpc/backend/backend.go
ethereum/rpc/namespaces/eth/api.go
x/evm/keeper/keeper.go
x/evm/keeper/state_transition.go
x/evm/keeper/statedb.go
x/evm/keeper/statedb_test.go
x/evm/types/key.go

Closes #67
- `SendTransaction` return eth tx hash to client
- `GetTransaction` convert eth hash to tm hash by calling `/tx_search`.
- Use eth tx hash internally
Verified in external integration test:
```
signed = eth_account.Account.sign_transaction(tx, VALIDATOR_PRIV_KEY)
txhash = w3.eth.sendRawTransaction(signed.rawTransaction)
assert txhash == signed.hash, 'invalid tx hash'
time.sleep(5)
tx = w3.eth.getTransactionReceipt(txhash)
print("tx receipt", tx)
```
______
______
For admin use:

return eth tx hash to client

---

ethereum/rpc/namespaces/eth/api.go
ethereum/rpc/types/utils.go
tests/rpc/rpc_pending_test.go
x/evm/types/msg.go
x/evm/types/utils.go
x/evm/types/utils_test.go

Closes #244
- also refactored repeatitive tx code.
______
______
For admin use:

Implement `eth_getPendingTransactions`

---

ethereum/rpc/apis.go
ethereum/rpc/backend/backend.go
ethereum/rpc/namespaces/eth/api.go
ethereum/rpc/namespaces/eth/filters/api.go
ethereum/rpc/namespaces/eth/filters/filter_system.go
ethereum/rpc/namespaces/eth/filters/filters.go
ethereum/rpc/namespaces/personal/api.go
ethereum/rpc/namespaces/txpool/api.go
ethereum/rpc/websockets.go
server/start.go
tests/solidity/init-test-node.sh
testutil/network/util.go

closes #262
there are still some logs from the log go-ethereum library that doesn't have a function for defining log level on the RPC handler

rpc: fix inconsistent logging levels

---

CHANGELOG.md
ethereum/rpc/backend/backend.go
ethereum/rpc/types/utils.go
x/evm/keeper/state_transition.go

Closes: #248
When blockbloom is nil and empty it is currently returning an error. We should return an empty bloom instead to avoid breaking other functionnalities.
Note that I have notice a weird behavior with the context (which return a blockboom at currentheight-1 when context is set at current height but it cannot be found is context is set at current height -1
______
______
For admin use:

Fix blockbloom in header error

---

x/evm/types/params.go

Closes: #287
Remove the extra eips since we already activated Berlin hardfork in chain config.
Why wrong order cause issue:
- eip1884 set `SLOAD`'s constant gas to 800, without touch dynamic gas
- eip2929 change `SLOAD` to use dynamic gas(2100 for cold access) and set constant gas to zero
So in the right order, the end result is 2100, but in reverse order, we get 2900.
Verified in external integration test.
______
______
For admin use:

fix order of eip activation

---

CHANGELOG.md
app/ante/eth.go
x/evm/keeper/grpc_query.go
x/evm/keeper/state_transition.go
x/evm/keeper/state_transition_test.go

noticed that the address was empty for the COINBASE opcode

evm: use block proposer address for COINBASE opcode

---

.github/workflows/goreleaser.yml
.goreleaser.yml
Makefile
go.mod
go.sum

Closes #296 
Add a goreleaser github action workflow.
______
______
For admin use:

feat: add goreleaser workflow

---

docs/architecture/adr-001-state.md
ethereum/rpc/backend/backend.go
ethereum/rpc/types/utils.go
init.sh
tests/solidity/init-test-node.sh
types/block.go
x/evm/keeper/state_transition.go

Closes: #302
- Set correct block gas limit in Block response (GetBlockByNB and GetBlockByHash)/
- Set correct block gas limit in evm parameters
- Fix hash function in evm parameters
______
______
For admin use:

fix evm parameters and block gas limit in getBlockByHeight and getBlockByHash

---

init.sh

Problem: CreationCode makes ethermintd exploded (fix #308)

---

x/evm/keeper/abci.go

The previous code is not incorrect since the method `SetBlockBloom` use the `ctx` passed in rather than the `k.ctx`.
It's confusing that sometimes methods use ctx in parameter, sometimes use `k.ctx`, but that's another issue.
______
______
For admin use:

fix a typo in context parameter

---

ethereum/rpc/backend/backend.go

Closes #318
abci app state could lag behind tendermint reported latest block number.
______
______
For admin use:

return abci state's latest block number in rpc

---

CHANGELOG.md
Makefile
client/keys/add.go

default `--algo eth_secp256k1` still not working (see https://github.com/cosmos/cosmos-sdk/issues/9734).
For cosmos key:
```
ethermintd keys add test --algo secp256k1 --coin-type 118 --ledger
```

keys: fix `secp256k1` key creation

---

docs/basics/json_rpc.md

Closes: #77
Fix documentation (lets close #77)
______
______
For admin use:

fix rpc documentation

---

CHANGELOG.md
x/evm/keeper/keeper.go
x/evm/keeper/statedb_test.go

Closes: #342 
______
______
For admin use:

keep balance when override account

---

CHANGELOG.md
x/evm/keeper/keeper.go
x/evm/keeper/statedb.go
x/evm/keeper/statedb_test.go
x/evm/types/key.go
x/evm/types/logs.go

Closes #334
______
______
For admin use:

chaneg log index to the index in block

---

ethereum/rpc/types/utils.go
tests/rpc/rpc_test.go

Closes: #380 
Small change to comply with Ethereum format on `extraData` field
______
______
For admin use:

fix: Extra data empty response

---

server/config/toml.go

Closes: #382
Viper has an issue reading string slice from environment variable when a flag with same value is defined (when no flag is defined, then there is no bug)
https://github.com/spf13/viper/issues/380
for example 
`["api", "personnal", "debug"]` would be parse to an array of length 1  with value [ "[api personnal debug]"]
Correct result should be ["api", "personnal", "debug"]
There is currently no fix for this issue yet, so I had to change the way we define the api in the app.toml
Using this trick, the parse will be successfull
______
______
For admin use:

fix viper parse app.toml

---

x/evm/keeper/state_transition.go

Closes: #414
______
______
For admin use:

re-emit the cosmos events from cache context

---

CHANGELOG.md
tests/solidity/suites/exception/contracts/TestRevert.sol
tests/solidity/suites/exception/contracts/test/Migrations.sol
tests/solidity/suites/exception/migrations/1_initial_migration.js
tests/solidity/suites/exception/package.json
tests/solidity/suites/exception/test/revert.js
tests/solidity/suites/exception/truffle-config.js
x/evm/keeper/context_stack.go
x/evm/keeper/grpc_query.go
x/evm/keeper/keeper.go
x/evm/keeper/state_transition.go
x/evm/keeper/statedb.go
x/evm/keeper/statedb_test.go

Closes: #338 
______
______
For admin use:

use stack of contexts to implement snapshot revert

---

go.mod
go.sum

Closes #311
______
______
For admin use:

Upgrade panicwrap for build issue fix

---

ethereum/rpc/namespaces/eth/api.go
tests/rpc/rpc_pending_test.go

Closes: #413
Fix get transaction by hash
______
______
For admin use:

fix get transaction by hash

---

app/ante/ante.go
x/evm/keeper/state_transition.go

Closes: #335
______
______
For admin use:

prepare access list for eth_call

---

log/handler.go
server/start.go

Solution: override with callback function

Problem: fix eth log override #343

---

docs/architecture/README.md
docs/architecture/adr-002-evm-hooks.md

ref impl: https://github.com/tharsis/ethermint/pull/417
______
______
For admin use:

Add adr-002 evm hooks proposal

---

server/start.go

It's better to always close the db before exit, so we will be noticed
when any error happens. Otherwise, serious errors can silently happen,
e.g, corrupted db, pending write missing ...
Fixes #538
______
______
For admin use:

server: add missing db.Close calls before returning

---

client/config.go
client/config_test.go

Catches and returns unhandled errors after stat-ing for the config file,
which is currently assuming that on non-existent error returned.
Fixes #539
______
______
For admin use:

client: catch and return unhandled errors in InitConfig

---

go.mod
x/evm/keeper/abci.go
x/evm/keeper/msg_server.go
x/evm/keeper/state_transition.go
x/feemarket/keeper/abci.go

all: remove telemetry

---

client/keys.go
server/flags/flags.go

Closes: #511 
Update the default keyring-backend to `os`
______
______
For admin use:

Problem: default keyring-backend not consistent with cosmos-sdk

---

CHANGELOG.md
server/util.go

`export` and `start` commands should use the same homedir.
______
______
For admin use:

fix: homedir consistency

---

ethereum/rpc/backend/backend.go
x/evm/keeper/state_transition.go

Closes: #575
- convert tx hash when query tx logs
- transaction index in tx logs should start from 0
______
______
For admin use:

tx receipt don't contains events

---

CHANGELOG.md
x/evm/keeper/benchmark_test.go
x/evm/keeper/state_transition_benchmark_test.go
x/evm/keeper/statedb_benchmark_test.go

Redo PR from https://github.com/tharsis/ethermint/pull/577

Benchmark evm keeper 

---

CHANGELOG.md
x/evm/keeper/grpc_query_test.go
x/evm/keeper/keeper.go
x/evm/keeper/statedb.go
x/evm/types/key.go

Closes: #589
- don't hash the key again in InitGenesis
______
______
For admin use:

Problem: import/export genesis roundtrip test fails for contract storage

---

CHANGELOG.md
ethereum/rpc/backend/backend.go
ethereum/rpc/namespaces/eth/filters/api.go
ethereum/rpc/namespaces/eth/filters/filters.go
tests/rpc/rpc_test.go

apply bloom filter when query ethlogs with range of blocks

---

ethereum/rpc/backend/backend.go

Closes: #573
Instead of doing multiple conversions in the loop, use a global []byte slice of evmtypes.AttributeKeyEthereumBloom.
______
______
For admin use:

fix: use global []byte slice to avoid sring -> []byte conversions in loop

---

CHANGELOG.md
encoding/config.go
encoding/config_test.go

Closes: #711
______
______
For admin use:

remove MsgEthereumTx support in TxConfig

---

CHANGELOG.md
rpc/ethereum/namespaces/eth/api.go
x/evm/client/cli/tx.go
x/evm/module.go
x/evm/types/msg.go
x/evm/types/msg_test.go

Closes #709
______
______
For admin use:

feat: add tx cli to build evm transaction

---

CHANGELOG.md
rpc/ethereum/namespaces/eth/api.go

#714 removed MsgEthereumTx support in TxConfig, so cannot use TxConfig to decode raw transactions.
______
______
For admin use:

Decode raw transaction via RLP

---

CHANGELOG.md
app/ante/ante.go
app/ante/ante_test.go
app/ante/eth.go
app/ante/sigs_test.go

Closes: #426
Sorry for accidentally closing the PR #689 .
The separate test for comparing signatures in cosmos tx , MsgEthereumTx and eth tx has been added.
______
______
For admin use:

fix: Some fields in transaction are not authenticated by signature

---

CHANGELOG.md
rpc/ethereum/namespaces/personal/api.go
tests/rpc/personal_test.go

Closes #738 
* this is aimed at smartcard wallet which is not supported yet.
* this is aimed at smartcard wallet which is not supported yet.
* an error with unsupported message will be returned for now.
______
______
For admin use:

Problem: need to add JSON-RPC endpoint personal_initializeWallet

---

CHANGELOG.md
client/keys.go

in adding key,
config/client.toml backend is not used 
1. adding key <- config/client.toml not used
2. list key <- config/client.toml used

Problem: cli keyring-backend not working correctly (fix #724)

---

CHANGELOG.md
init.sh
rpc/ethereum/backend/backend.go
rpc/ethereum/namespaces/debug/api.go

Closes #742 and closes #744
Add the missing method
______
______
For admin use:

Problem: Missing debug_tranceBlockByHash RPC method and debug_traceBlock* may crash on non-existing block

---

CHANGELOG.md
rpc/ethereum/namespaces/personal/api.go
tests/rpc/personal_test.go

Closes #745
* wallet level that manages accounts is not supported by keyring interface, will return nil
______
______
For admin use:

Problem: need to add JSON-RPC endpoint personal_listWallets

---

CHANGELOG.md
rpc/ethereum/namespaces/debug/api.go

Closes #715
* currently return emtpy hash
Closes: #XXX
______
______
For admin use:

Problem: need to add JSON-RPC endpoint debug_intermediateRoots

---

CHANGELOG.md
x/evm/handler_test.go
x/evm/keeper/state_transition.go

Problem: When there are hooks and the transaction reverted, gas refund logic is reverted too.
Solution: Don't revert the gas refund logic
______
______
For admin use:

fix: don't revert gas refund logic when transaction reverted

---

CHANGELOG.md
tests/rpc/rpc_pending_test.go
tests/rpc/rpc_test.go
tests/rpc/utils.go
x/feemarket/types/params.go

Closes: [ENG-273 RPC tests are failing if FeeMarket Base Fee is enabled by default](https://linear.app/tharsis/issue/ENG-273/rpc-tests-are-failing-if-feemarket-base-fee-is-enabled-by-default)
This PR enables the FeeMarket `BaseFee` by default and fixes the failing rpc tests by replacing the hardcoded `gasPrice`

RPC tests are failing if FeeMarket Base Fee is enabled by default

---

CHANGELOG.md
app/ante/ante.go
app/ante/eth.go
go.mod
go.sum
rpc/ethereum/backend/backend.go
rpc/ethereum/namespaces/eth/api.go
rpc/ethereum/namespaces/miner/api.go
x/evm/keeper/grpc_query.go
x/evm/keeper/keeper.go
x/evm/keeper/msg_server.go
x/evm/keeper/state_transition.go
x/evm/keeper/utils.go
x/evm/types/chain_config.go

Closes: #785
Solution:
- Remove the stacktrace dependency, use `sdkerrors.Wrap`,
since cosmos-sdk already support extract stacktrace in debug mode.
______
______
For admin use:

improve error message in `SendTransaction` json-rpc api

---

CHANGELOG.md
cmd/ethermintd/root.go
x/evm/keeper/migrations.go
x/evm/module.go
x/feemarket/keeper/migrations.go
x/feemarket/module.go

feat: store migration setup

---

CHANGELOG.md
testutil/network/util.go
x/evm/keeper/keeper.go
x/evm/keeper/statedb.go
x/evm/keeper/statedb_test.go

Solution:
- reversed the semantic of return value of the callback function.
ref: https://github.com/ethereum/go-ethereum/blob/master/core/state/statedb.go#L637
______
______
For admin use:

Problem: ForEachStorage sematic not compatible with go-ethereum

---

CHANGELOG.md
x/evm/keeper/msg_server.go

Uses the fastest slice making idiom of creating the well known
size of a slice using
make([]sdk.Attribute, len(response.Logs))
for i, log := range response.Logs {
txLogAttrs[i] = ...
}
instead of
make([]sdk.Attribute, 0)
for _, log := range response.Logs {
txLogAttrs = append(txLogAttrs, ...)
}
which had a few problems:
1. Using 0 for size then appending is quite slow yet we know the exact size
2. Using append instead of indexing is slower
If we examine the advisory at https://bencher.orijtech.com/perfclinic/sliceupdate/
and the verdict at https://bencher.orijtech.com/perfclinic/sliceupdate/#verdict
this new scheme shows a massive improvement in that call site.
Fixes #825

x/evm/keeper: use the fastest slice making idiom for Keeper.EthereumTx.Logs

---

x/evm/types/access_list_tx.go
x/evm/types/dynamic_fee_tx.go
x/evm/types/legacy_tx.go

Following suit with PR #828, this change cuts down the expenses
from using .To doubly; yet using the Go in-condition variable idiom.
Updates #826

x/evm/types: use ethtypes.Transaction.To for cheaper retrieval

---

CHANGELOG.md
x/evm/types/tracer.go

This change fixes an insidious bug that unfortunately
tried to split values in multiples of 32, but unfortunately
due to the loop conditions, if the length of trace.Memory
was less than 32, nothing would be added; if the value wasn't
a multiple of 32, the ends wouldn't be added in.
Fixes #837

x/evm/types: properly split in 32 chunks trace.Memory

---

CHANGELOG.md
app/ante/ante.go

They are already checked in [EthValidateBasicDecorator](https://github.com/tharsis/ethermint/blob/main/app/ante/eth.go#L476)
______
______
For admin use:

remove redundant ante handler

---

CHANGELOG.md
rpc/ethereum/backend/utils.go

backport https://github.com/tharsis/ethermint/pull/840 in a non-breaking way.
______
______
For admin use:

fix empty topics in a non-breaking way (#35)

---

rpc/ethereum/types/utils.go

Closes: #853
Solution:
- only set baseFeePerGas when base fee is not nil.
following go-ethereum logic: https://github.com/ethereum/go-ethereum/blob/master/internal/ethapi/api.go#L1211
______
______
For admin use:

Problem: web3 client don't expect a null baseFeePerGas

---

CHANGELOG.md
tests/rpc/rpc_test.go
x/evm/handler_test.go
x/evm/keeper/keeper_test.go
x/evm/keeper/state_transition.go
x/evm/keeper/state_transition_test.go
x/evm/types/tx_args.go

Closes: #850
- reset sender.nonce before evm.create
- add unit tests and rpc tests
How the nonce is changed:
```
Ante handler:
check(tx.nonce == sender.nonce)
sender.nonce += 1
ApplyMessage:
if contract_creation {
sender.nonce = tx.nonce
err := evm.create(...)
sender.nonce = tx.nonce + 1
} else {
evm.call(...)
}
```
Two contraints for the design:
- sender's nonce should be increased even if `ApplyMessage` fails.
- `sender.nonce` should be equal to `tx.nonce` when calling `evm.create`, so the contract address will be correct.
______
______
For admin use:

fix: contract address in contract creation receipt is wrong

---

CHANGELOG.md
rpc/ethereum/backend/backend.go
rpc/ethereum/namespaces/eth/filters/api.go
rpc/ethereum/namespaces/eth/filters/filters.go
rpc/ethereum/namespaces/eth/filters/utils.go
server/config/config.go
server/config/toml.go
server/flags/flags.go
server/start.go

Closes: #858, #861
- add limit to number of logs of filter response
- make block limit and log limit configurable
- fix empty response when specifying blockHash but without address/topics filter critiera.
______
______
For admin use:

fix: OOM when eth_getLogs response too large

---

CHANGELOG.md
rpc/ethereum/namespaces/eth/filters/api.go

Closes: #792 
Criteria's were missing on filter creation
______
______
For admin use:

Add criteria to filter

---

CHANGELOG.md
x/evm/keeper/grpc_query.go
x/evm/keeper/grpc_query_test.go
x/evm/keeper/keeper_test.go

Closes: #870
for contract creation tx, the executing msg must contain the correct nonce value, because `ApplyMessage` will reset sender's nonce to that first.
______
______
For admin use:

fix: set correct nonce in EthCall/EstimateGas

---

CHANGELOG.md
x/evm/genesis.go
x/evm/genesis_test.go

Closes: #872
______
______
For admin use:

Validate code hash in GenesisAccount

---

CHANGELOG.md
rpc/ethereum/backend/backend.go

Closes: #877
Solution:
- workaround at rpc side, ignore the gasUsed in such cases.
______
______
For admin use:

GetBlock rpc api report wrong gasUsed

---

x/evm/statedb/access_list.go
x/evm/statedb/mock_test.go
x/evm/statedb/state_object.go
x/evm/statedb/statedb.go
x/evm/statedb/statedb_test.go

Closes: #876
- coverage: 99.3% of statements
The only two lines of code that is not covered are unreachable practically I believe:
- https://github.com/tharsis/ethermint/blob/main/x/evm/statedb/access_list.go#L116, access list journals are always in correct order.
- https://github.com/tharsis/ethermint/blob/main/x/evm/statedb/statedb.go#L292, `len(value)` is always positive.
______
______
For admin use:

Impove test coverage of x/evm/statedb package

---

x/evm/keeper/keeper_test.go

Closes: #536
Solution: Use a fixed test account.
The source of non-deterministic is tx's intrinsic gas is different according to a different number of zeros in input data, and the randomly generated test address is included in that.
so to make sure the gas number is reproducible, we need to use a constant test accont.
______
______
For admin use:

Make gas estimation test reproducible

---

CHANGELOG.md
rpc/ethereum/types/utils.go
rpc/websockets.go
server/json_rpc.go

Closes: #899
Solution:
- return the eth tx hash
______
______
For admin use:

Problem: newPendingTransactions filter don't return ethereum tx hash

---

CHANGELOG.md
app/ante/ante_test.go
app/ante/eth.go
app/ante/eth_test.go
app/ante/handler_options.go
app/ante/interfaces.go
rpc/ethereum/backend/backend.go
rpc/ethereum/backend/utils.go
rpc/ethereum/namespaces/eth/api.go
rpc/ethereum/namespaces/eth/filters/api.go
rpc/ethereum/types/utils.go
rpc/websockets.go
x/evm/client/rest/rest.go
x/evm/keeper/keeper.go
x/evm/keeper/msg_server.go
x/evm/keeper/state_transition.go
x/evm/spec/02_state.md
x/evm/spec/07_events.md
x/evm/types/events.go
x/evm/types/key.go
x/evm/types/utils.go
x/evm/types/utils_test.go

Closes: #896
Allow multiple MsgEthereumTx in a single tx
______
______
For admin use:

support batch eth tx

---

rpc/ethereum/namespaces/debug/api.go
rpc/ethereum/namespaces/eth/api.go
rpc/ethereum/types/utils.go

Closes: #906
______
______
For admin use:

make trace transaction api work with batch tx

---

app/ante/eth.go

Closes: #910
error message should be "insufficient fee" when gas price set too low
______
______
For admin use:

fix insufficient fee error message

---

CHANGELOG.md
init.sh
server/flags/flags.go
server/start.go
tests/solidity/init-test-node.sh

Closes: #771 
Add `api.enable` flag to enable Cosmos REST server. At the moment this is only possible by modifying `app.toml` file.
______
______
For admin use:

add api.enable flag for Cosmos SDK Rest server

---

CHANGELOG.md
x/evm/keeper/keeper_test.go
x/evm/keeper/state_transition_test.go
x/feemarket/keeper/grpc_query_test.go
x/feemarket/types/genesis.go

Closes: #918
Solution:
- initialise the default base fee value in genesis
______
______
For admin use:

fix: default base fee state in genesis

---

.github/workflows/build.yml
.github/workflows/deploy-contract.yml
.github/workflows/test.yml
Makefile
scripts/integration-test-all.sh
scripts/start.sh
tests/e2e/integration_test.go

We will be retiring `rpc` tests pretty soon so this job separates out the e2e tests and `rpc` tests in different workflows. When and if we are ready to retire the `rpc` tests we can go ahead and remove the `rpc` workflow. 
______
______
For admin use:

ci: separate out rpc and integration tests

---

app/ante/eth.go

Closes: #XXX
I think `// - the transaction contains more than one message` is wrong comment.
Can't one tx contain multiple Msgs?
It seems like it just needs to be of type MsgEthereumTx.
______
______
For admin use:

fix: wrong comment in EthGasConsumeDecorator

---

CHANGELOG.md
server/json_rpc.go

Closes: #862
Map go-ethereum's log levels to tendermint ones:
trace -> debug
debug -> debug
info -> info
warn -> info
error -> error
crit -> error
______
______
For admin use:

redirect go-ethereum's logs to cosmos logger

---

CHANGELOG.md
rpc/ethereum/namespaces/eth/api.go

Closes: #XXX
Adding support for the `eth_signedTypedData` for EIP 712 support. Was not able to add integration tests as it its not inclided in the JSONRPC geth interface. We might be able to work around this once we have OpenRPC support.
______
______
For admin use:

Add support for `eth_signedTypedData`

---

CHANGELOG.md
rpc/ethereum/backend/backend.go
rpc/ethereum/backend/utils.go
rpc/ethereum/namespaces/eth/api.go

Closes: #967
Solution:
- add 1/8 buffer on top of base fee for default gas price
Closes: #XXX
______
______
For admin use:

Problem: Metamask keeps failing sending transactions

---

CHANGELOG.md
rpc/ethereum/backend/feebackend.go

Closes: #XXX
Querying the `eth_feeHistory` can return a `reward` attribute with `null` values, as seen with:
```
curl https://eth.bd.evmos.org:8545 \
-X POST \
-H "Content-Type: application/json" \
-d '{"jsonrpc":"2.0","method":"eth_feeHistory","params":["0x4", "0x3a6e", [25, 75]],"id":1}'
```
```
{"jsonrpc":"2.0","method":"eth_feeHistory","params":["0x4", "0x3a6e", [25, 75]],"id":1}'
{"jsonrpc":"2.0","id":1,"result":{"oldestBlock":"0x3a6a","reward":[[null,null],[null,null],[null,null],[null,null]],"baseFeePerGas":["0x7","0x7","0x7","0x7"],"gasUsedRatio":[0.0034889,0.01266025,0.019304325,0.0153471]}}
```
Even if the block does not have transactions, the value should always be `0x0`.
______
______
For admin use:

eth_feeHistory reward values cannot be nil

---

CHANGELOG.md

Closes: #XXX
______
______
For admin use:

release: changelog

---

CHANGELOG.md
rpc/ethereum/backend/feebackend.go

Quick fix for https://github.com/tharsis/ethermint/issues/974, but does not fix the underlying issue.
Closes: #XXX
`RPC method eth_feeHistory crashed: runtime error: invalid memory address or nil pointer dereference`
from https://github.com/tharsis/ethermint/blob/caa1c5a6c6b7ed8ba4aaf6e0b0848f6be5ba6668/rpc/ethereum/backend/feebackend.go#L29
______
______
For admin use:

Quick fix for eth_feeHistory when reward is nil

---

CHANGELOG.md
server/config/config.go
server/config/toml.go
server/flags/flags.go
server/json_rpc.go
server/start.go

Closes: #963
not tested yet.
______
______
For admin use:

Add configurable timeouts to http server

---

CHANGELOG.md
rpc/ethereum/backend/feebackend.go

Problem:
- rewards calculation based on percentiles took into consideration the tendermint tx count instead of `MsgEthereumTx` count.
- `sorter := make(sortGasAndReward, tendermintTxCount)` creates an array of `{0 <nil>}` values.
The `nil` value from the `reward` attribute was never rewritten for tendermint Tx without any `MsgEthereumTx`
Fixes:
- return early if there are 0 `MsgEthereumTx`, as in:
https://github.com/ethereum/go-ethereum/blob/57cec892536270fc6dafae01ded2c528ffa370e9/eth/gasprice/feehistory.go#L106-L113
- use the `MsgEthereumTx` count to calculate rewards
Fixes https://github.com/tharsis/ethermint/issues/974
Closes: #XXX
______
______
For admin use:

eth_feeHistory - fix reward calculation from MsgEthereumTx

---

CHANGELOG.md
server/start.go

Closes: #987
Solution:
- use local rpc clint if json-rpc is enabled.
Closes: #XXX
______
______
For admin use:

json-rpc server should always use local rpc client

---

CHANGELOG.md
app/ante/eth.go
app/ante/eth_test.go

Closes: #989
the gasWanted returned in check tx is set to `min(500000, msg.GetGas())`.
______
______
For admin use:

Set an upper bound to gasWanted to prevent DoS attack

---

x/feemarket/keeper/migrations.go
x/feemarket/keeper/migrations_test.go
x/feemarket/module.go

Closes: #1001
Add the migration handler to remove the unused state key.
______
______
For admin use:

increase feemarket's consensus version and add migration handler

---

CHANGELOG.md
app/ante/eth.go
app/ante/eth_test.go
app/ante/handler_options.go
app/app.go
server/config/config.go
server/config/toml.go
server/flags/flags.go
server/start.go

Closes: #1003
Solution:
- add config item: evm.max-tx-gas-wanted
______
______
For admin use:

make MaxTxGasWanted configurable

---

CHANGELOG.md
rpc/ethereum/namespaces/web3/api.go
tests/e2e/integration_test.go
tests/rpc/rpc_test.go

Fixes: #632 
Solution:
Before the fix, the "web3_sha3" JSON_RPC endpoint will overwrite the "0x" as "" by using "hexutil.Bytes" as the input parameters, then return same result. After the fix, using "string" as the input parameters will avoid the overwrite and return correct response.
______
______
For admin use:

fix: Update the JSON-RPC to correct the return information.

---

CHANGELOG.md
rpc/apis.go
rpc/ethereum/namespaces/eth/filters/api.go
tests/e2e/integration_test.go
testutil/network/util.go

Closes: #1011
Solution:
- use eth tx hash rather than tendermint one
tested with this integration test: https://github.com/crypto-org-chain/cronos/pull/404/files#diff-126ee319c6fd3229b0d12d6e6110955bd64ea6a419086f618a06dedd1234fc68R15
______
______
For admin use:

Problem: eth_newPendingTransactionFilter don't return correct tx hash

---

x/evm/types/storage.go
x/evm/types/storage_test.go

Closes: #XXX
______
______
For admin use:

evm: update empty hash check for storage state

---

CHANGELOG.md
x/evm/handler_test.go
x/evm/keeper/hooks.go
x/evm/keeper/hooks_test.go
x/evm/keeper/keeper.go
x/evm/keeper/state_transition.go
x/evm/types/interfaces.go

Closes: #XXX
Give access to both message and receipt in the `PostTxProcessing` hook.
______
______
For admin use:

evm: PostTxProcessing hook - include the full message data

---

x/evm/types/dynamic_fee_tx_test.go

Addresses: #1017 
Hi, I want to start contributing to the repo and figured writing tests is a good way to start.
Please point me towards any improvements I can make for future PRs and changes that are necessary for this PR to be accepted.
I have added a test for the `AsEthereumData` method of `DynamicFeeTx` and some edge case tests regarding overflowing `big.Int`s.
______
______
For admin use:

tests: Add more dynamic fee tx tests

---

CHANGELOG.md
rpc/apis.go
server/config/config.go

Closes: #1052, #1037
An example of usage: https://github.com/crypto-org-chain/cronos/pull/432/files#diff-7acb7332ad576a49e7685db72282959006f156c06a708828d8b0b187e311ffe1R32
______
______
For admin use:

make jsonrpc api namespaces extensible

---

CHANGELOG.md
app/ante/ante_test.go
app/ante/eth.go
app/ante/utils_test.go

WIP: #1045
Reject tx early in ante handler, avoid deduct user fee for vain.
______
______
For admin use:

Check EnableCreate/EnableCall in ante handler

---

CHANGELOG.md
rpc/backend/evm_backend.go
rpc/namespaces/ethereum/eth/api.go

Solution:
- pass the correct baseFee parameter to function NewTransactionFromMsg
______
______
For admin use:

fix: gas price returned in getTransaction api

---

CHANGELOG.md
x/evm/keeper/state_transition.go

Closes: #XXX
Following https://github.com/tharsis/ethermint/pull/1025 ,
The result is not updated properly and the additional log in tx post processing are not persisted
______
______
For admin use:

Fix ability to append log in tx post processing 

---

CHANGELOG.md
rpc/backend/evm_backend.go
rpc/namespaces/ethereum/eth/api.go
rpc/namespaces/ethereum/eth/filters/api.go
rpc/namespaces/ethereum/eth/filters/filters.go
rpc/types/utils.go

deduplicate some codes
______
______
For admin use:

clean up the block fetch logic in json-rpc

---

CHANGELOG.md
go.mod
x/evm/keeper/msg_server.go

This PR adds telemetry for Ethereum txs. This functionality was originally removed with https://github.com/tharsis/ethermint/pull/545/files because of performance issues with `telemetry.ModuleMeasureSince`, which are not readded.

impr(evm): add tx_type, gas and counter telemetry for ethereum txs

---

CHANGELOG.md
x/evm/keeper/msg_server.go
x/evm/keeper/state_transition.go
x/feemarket/keeper/abci.go

This PR adds telemetry to Ethermint modules and is an advancement of the recent [telemetry implementation on Evmos](https://github.com/tharsis/evmos/pull/637).
I implemented the following metrics to observe. They still need to be  added  to the respective specs that use Ethermint:
| Metric                                      | Description                                      | Unit  | Type  |
| :------------------------------------------ | :----------------------------------------------- | :---- | :---- |
| `feemarket_base_fee`                        | Amount of base fee per EIP-1559 block            | token | gauge |
| `feemarket_block_gas`                       | Amount of gas used in an EIP-1559 block           | token | gauge |
| `tx_msg_ethereum_tx_gas_limit_per_gas_used` | Ratio of …

analytics(app): update telemetry to Ethermint modules

---

CHANGELOG.md
rpc/backend/backend.go
rpc/backend/evm_backend.go
rpc/namespaces/ethereum/eth/api.go

This PR aims to update GetGasPrice API with the new GlobalMinGasPrice module param. The idea is to return this value as minimum for transactions to adjust to the new decorator.
______
______
For admin use:

Update GetGasPrice RPC endpoint with global `MinGasPrice`

---

CHANGELOG.md
app/ante/handler_options.go

Closes: #XXX
Small change to move the CanTransfer (checks if the sender is allowed to transfer funds) decorator before the GasConsume decorator.
______
______
For admin use:

Move CanTransfer decorator before GasConsume

---

CHANGELOG.md
types/account.go

* this change is related to https://github.com/cosmos/cosmos-sdk/pull/12154/files
* for more info see https://github.com/crypto-org-chain/cronos/issues/471
Closes: #XXX
______
______
For admin use:

avoid invalid account error on create vesting account

---

CHANGELOG.md
types/account.go
types/account_test.go

Closes: #XXX
Fix empty code hash comparison on account Type() method
______
______
For admin use:

fix account type method

---

CHANGELOG.md
rpc/apis.go
rpc/backend/backend.go
rpc/backend/evm_backend.go
rpc/namespaces/ethereum/eth/api.go
server/config/config.go
server/config/toml.go
server/flags/flags.go
server/json_rpc.go
server/start.go

Closes: #XXX
______
______
For admin use:

imp(rpc): restrict unprotected txs on the node RPC

---

.mergify.yml
CHANGELOG.md

- release: v0.17.0 changelog (#1153)
- update mergify
Closes: #XXX
______
______
For admin use:

release: backport changelog

---

CHANGELOG.md
Makefile
x/feemarket/spec/01_concepts.md

This PR adds a hint in the specs about different gas terminology for gas in Cosmos and Ethereum.

feemarket(specs): add hint on different gas terminology for gas in Cosmos and Ethereum

---

app/app_test.go
app/benchmark_test.go
app/utils.go
x/evm/handler_test.go
x/evm/keeper/keeper_test.go
x/feemarket/keeper/integration_test.go

Extracted from: https://github.com/evmos/ethermint/pull/1168
In cosmos-sdk 0.46's InitGenesis it reject Zero validators,
prepare for the upgrade of cosmos-sdk 0.46.
______
______
For admin use:

Setup a validator in the test genesis

---

CHANGELOG.md
app/app.go
client/testnet.go
ethereum/eip712/eip712.go
go.sum
rpc/ethereum/backend/backend.go
rpc/ethereum/backend/feebackend.go
rpc/ethereum/namespaces/eth/api.go
tests/importer/chain_ctx.go

This PR backports a patch for the `eth_getBalance` JSON-RPC endpoint in order to query historical archive nodes:
- fix(rpc): optimize `eth_getBalance` endpoint (#1169)
Related issue: https://linear.app/evmos/issue/ENG-577/release-ethermint-and-evmos-patches-for-historical-archive-nodes

release: v0.10.2 changelog with backport

---

CHANGELOG.md
rpc/ethereum/backend/backend.go
rpc/ethereum/namespaces/eth/api.go

This PR backports a patch for the `eth_getBalance` JSON-RPC endpoint in order to query historical archive nodes:
- fix(rpc): optimize `eth_getBalance` endpoint (#1169)
Related issue: https://linear.app/evmos/issue/ENG-577/release-ethermint-and-evmos-patches-for-historical-archive-nodes

release: v0.14.1 changelog and backport

---

CHANGELOG.md
rpc/backend/backend.go
rpc/backend/evm_backend.go
rpc/namespaces/ethereum/eth/api.go

This PR backports a patch for the `eth_getBalance` JSON-RPC endpoint in order to query historical archive nodes:
- fix(rpc): optimize `eth_getBalance` endpoint (#1169)
Related issue: https://linear.app/evmos/issue/ENG-577/release-ethermint-and-evmos-patches-for-historical-archive-nodes

release: v0.16.2 changelog and backport

---

CHANGELOG.md
rpc/backend/backend.go
rpc/backend/evm_backend.go
rpc/namespaces/ethereum/eth/api.go

This PR backports a patch for the `eth_getBalance` JSON-RPC endpoint in order to query historical archive nodes:
- fix(rpc): optimize `eth_getBalance` endpoint (#1169)
Related issue: https://linear.app/evmos/issue/ENG-577/release-ethermint-and-evmos-patches-for-historical-archive-nodes

release: v0.17.1 changelog and backport

---

rpc/backend/evm_backend.go

closes: #1222
Integration tests to be added in: https://github.com/evmos/ethermint/pull/1212
______
______
For admin use:

fix pruned node integration test

---

CHANGELOG.md
app/ante/eth.go
app/ante/eth_test.go
app/ante/handler_options.go
app/ante/interfaces.go
default.nix
go.mod
go.sum
gomod2nix.toml
rpc/backend/evm_backend.go
rpc/namespaces/ethereum/eth/api.go
tests/integration_tests/configs/default.jsonnet
tests/integration_tests/network.py
tests/integration_tests/test_priority.py
tests/integration_tests/utils.py
x/evm/handler_test.go
x/evm/keeper/integration_test.go
x/evm/keeper/keeper.go
x/evm/keeper/utils.go
x/evm/keeper/utils_test.go
x/evm/types/access_list_tx.go
x/evm/types/dynamic_fee_tx.go
x/evm/types/legacy_tx.go
x/evm/types/tx_data.go
x/feemarket/keeper/integration_test.go
x/feemarket/spec/09_antehandlers.md

Set the tx priority to the lowest priority in the messages.
______
______
For admin use:

Set priority for eth transactions

---

CHANGELOG.md
Makefile
cmd/ethermintd/root.go
server/flags/flags.go
server/start.go

Build rocksdb enabled binary:
```
ENABLE_ROCKSDB=true COSMOS_BUILD_OPTIONS=rocksdb make build
```
Enable `app-db-backend` in `app.config`, or use  cli flag:`ethermintd start --app-db-backend "rocksdb"`
______
______
For admin use:

feat: support dynamic app db backend flag

---

CHANGELOG.md
x/feemarket/client/cli/query.go

Solution:
- remove the positional height parameter, since there's a flag already.
______
______
For admin use:

Problem: feemarket's query cli has redundant height parameter

---

tests/integration_tests/test_types.py
tests/integration_tests/utils.py

it could fail for error "proof queries at height <= 2 are not supported"
if the latest block number <= 2
______
______
For admin use:

fix: make get_proof integration tests more stable

---

rpc/backend/backend.go
rpc/backend/node_info.go
rpc/namespaces/ethereum/miner/api.go

Closes: #XXX
This PR fixes a regression from the [RPC refractor](#1218). 
______
______
For admin use:

Add support for `miner_setGasPrice` API

---

tests/integration_tests/test_priority.py

Solution:
- increase the scale of priority numbers to make it more stable.
______
______
For admin use:

Problem: priority test result affect by base fee dropping

---

CHANGELOG.md
gomod2nix.toml
indexer/kv_indexer_test.go
rpc/backend/account_info.go
rpc/backend/backend.go
rpc/backend/node_info.go
rpc/namespaces/ethereum/eth/filters/api.go
rpc/namespaces/ethereum/miner/api.go
tests/integration_tests/README.md
tests/integration_tests/contracts/contracts/Greeter.sol
tests/integration_tests/network.py
tests/integration_tests/test_filters.py
tests/integration_tests/test_types.py
tests/integration_tests/utils.py

Closes: #XXX
Adding the following changes:
- #1237  
- #1239 
- #1233 
- Changelog update
- Updated gomod2nix
______
______
For admin use:

Cherry pick latest changes

---

CHANGELOG.md
rpc/backend/call_tx.go
tests/integration_tests/test_types.py

Closes: #XXX
Fix estimate gas rpc response error when height provided is in the future.
______
______
For admin use:

fix(rpc): estimate gas error response

---

CHANGELOG.md
app/ante/ante_test.go
app/ante/utils_test.go
ethereum/eip712/eip712.go

Closes: #XXX
The eip712 was missing some types necessary for the createValidator msg.
Added tests for several msgs for eip712.
______
______
For admin use:

!fix(erc712): support `MsgCreateValidator`

---

CHANGELOG.md
server/start.go
x/evm/keeper/grpc_query.go

Closes: #1007
- Initiate the GRPCClient introduced in [sdk 0.46](https://github.com/cosmos/cosmos-sdk/pull/11234).
Verified manually that it indeed worked (by adding a long sleep in one of the grpc query handlers).
______
______
For admin use:

imp(rpc,server): concurrent gRPC queries

---

app/ante/eth.go
x/evm/keeper/params.go
x/feemarket/keeper/params.go

A small refactor to the below reference PR. To avoid calling `params` for every message retrieve them before the loop. Additionally in order to stay consistent with the structure to the rest of the repo use detailed variable declaration
Closes: https://github.com/evmos/ethermint/pull/1388#pullrequestreview-1147926848
______
______
For admin use:

Antehandler optimization - revision

---

.github/workflows/build.yml
.github/workflows/goreleaser.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.golangci.yml
CHANGELOG.md
Makefile
README.md
go.mod
go.sum
networks/local/ethermintnode/Dockerfile

See https://github.com/evmos/evmos/pull/1023:
> When using go1.18 AND 1.19 (assuming validators have different go versions) there can be issues with mismatching snapshots when using state sync, confirmed by sdk team. The easiest way for evmos to avoid this issue, is to set the version of go to 1.19 at the time of a breaking change (like upgrading to 46).
> 
> This PR moves evmos to go 1.19 as of the upgrade that applies sdk 46, to ensure that 100% of validators are using go 1.19 since it is specified in go.mod.

deps: bump go to v1.19

---

CHANGELOG.md
cmd/ethermintd/genaccounts.go
x/evm/client/cli/query.go
x/evm/client/cli/tx.go
x/evm/spec/09_client.md
x/feemarket/client/cli/query.go
x/feemarket/spec/08_client.md

Closes: [ENG-832](https://linear.app/evmos/issue/ENG-832/apply-google-cli-syntax-for-required-and-optional-arguments)
Apply [Google CLI Syntax](https://developers.google.com/style/code-syntax) for required and optional args
______
______
For admin use:

chore(cli): apply google CLI Syntax for required and optional args

---

CHANGELOG.md

Part of: https://linear.app/evmos/issue/ENG-952/create-release-candidate-v0200-rc2-on-ethermint
Adds a changelog for `rc2` after we noticed that `rc1` did not include the latest sdk minor release.

release: v0.20.0-rc2 changelog

---

tests/integration_tests/configs/default.jsonnet
tests/integration_tests/test_pruned_node.py
tests/integration_tests/test_upgrade.py
tests/integration_tests/utils.py

Closes: #XXX
Reduce integration test block time to 2s to make test run faster.
______
______
For admin use:

imp: reduce integration test block time to 2s

---

tests/integration_tests/test_gas.py

Closes: [ENG-1034](https://linear.app/evmos/issue/ENG-1034/compare-geth-gas-consumption-on-integration-tests) (Linear)
- after #1460 , gas consumption on Ethermint should be similar to Geth
- added integration test to ensure that gas consumption when sending transactions is equivalent
______
______
For admin use:

tests: add gas consumption test

---

CHANGELOG.md
x/evm/keeper/msg_server.go

Closes: #1435 
This PR removes the labels `from` and `to` as these result in unbound cardinality as it will keep creating new metrics with every new `from` and `to` values received in the node.
______
______
For admin use:

Remove unbound labels from added custom tendermint metrics

---

CHANGELOG.md
go.mod
go.sum

Closes: #XXX
______
______
For admin use:

deps: bump SDK to v0.46.6

---

app/ante/ante.go
app/ante/eip712.go
app/ante/eth.go
app/ante/fee_checker.go
app/ante/fee_market.go
app/ante/fees.go
app/ante/handler_options.go
app/ante/mempool.go
app/ante/reject_msgs.go
app/ante/setup.go
app/ante/sigverify.go

In this PR, I have adjusted the deprecated Cosmos SDK error module imports.

Change deprecated SDK errors imports

---

x/evm/keeper/grpc_query_test.go

Closes: #XXX
The timeout traceTx test behaviour is inconsistent. It relies on the timeout thread to be assigned resources before the traceTx is executed.
If we want to keep this test, we need to find a way to make a super expensive tracetx call (but it may still behave the same way)
______
______
For admin use:

fix(tests): Delete inconsistent test

---

app/ante/utils_test.go

Closes: #XXX
Refactor `utils_test` import naming convention for better clarity.
______
______
For admin use:

chore: refactor imports naming for clarity

---

CHANGELOG.md
gomod2nix.toml
rpc/backend/utils.go
tests/integration_tests/test_account.py
tests/integration_tests/utils.py

Closes: #XXX
Should get empty result instead of account not found error like in `eth_getTransactionCount`:
- contract [address](https://testnet.cronoscan.com/address/0x16D88c870ffbe8F5deacD9a48d344b674F3486c7), can query since 1st creation tnx block 5044182
- non zero balance normal [address](https://testnet.cronoscan.com/address/0x8fe929c08d2445476599406db26717c3c0c0cb0a), can query since 1st tranfer block 6197517
______
______
For admin use:

fix: align empty account result for old blocks as ethereum

---

CHANGELOG.md
app/ante/eth.go
server/start.go

This PR fixes the telemetry setup on the Ethermint server, which is a fork of the Cosmos SDK one that also contains the JSON-RPC service
______
______
For admin use:

fix(server): telemetry setup

---

CHANGELOG.md
app/app.go

This PR mirrors evmos/evmos#1114 to set the default file store listener as proposed in Cosmos SDK's [ADR38](https://docs.cosmos.network/v0.47/architecture/adr-038-state-listening).
As it can be seen in the attached document, this enables "enable listening to state changes of individual KVStores and exposing these data to consumers."
----
Closes ENG-1090

chore(app): add store listener to Ethermint app

---

CHANGELOG.md
go.mod
go.sum

Closes: #XXX
Release Notes: https://github.com/ethereum/go-ethereum/releases/tag/v1.10.26
______
______
For admin use:

fix: Bump Go-Ethereum dependency to 1.10.26

---

CHANGELOG.md
app/app.go
ethereum/eip712/encoding.go

Closes: #[1161](https://linear.app/evmos/issue/ENG-1161/improve-error-handling-for-eip-712-encoding-config-panic)
Fix the panic associated with unset codecs by checking to ensure the codecs were initialized, then returning an error if so. If the EIP-712 initialization is missing for any reason, at worst the code will not support EIP-712 transactions. Although this would still be a problem, it is much better than a kernel panic.
______
______
For admin use:

fix: improve error handling for EIP-712 encoding config init

---

x/evm/handler_test.go

Closes: n/a
fixes `TestDeployAndCallContract` which was not unmarshalling the correct handler result.
______
______
For admin use:

fix: use actual result when unmarshaling value

---

rpc/backend/sign_tx.go

This minor change improves the verbosity of the error, that occurs during a call to the `eth_sendTransaction` endpoint, should the sender address not be found in the used keyring.
Since Go-Ethereum is (at least to my knowledge) not concerned with using different keyring backends etc. as on Cosmos, the raised error is not too verbose. IMO this is a small improvement for developer experience.

imp (evm): make missing key error message during SendTransaction more verbose

---

rpc/backend/node_info.go

fix the internal parameter.
Shall we just deprecated the personal apis, since they are rarely used, and not well tested.
______
______
For admin use:

Problem: personal_newAccount don't work

---

CHANGELOG.md
app/ante/eth.go

Closes: 
- [Issue #1554](https://github.com/evmos/ethermint/issues/1554)
- https://linear.app/evmos/issue/ENG-1238/bug-not-calling-runtxdelivermode-after-runtxrecheckmode
Set `gasWanted = 0` for Txs in `ReCheckMode` at the `EthGasConsumeDecorator` AnteHandler. Otherwise, Tendermint logs this error:
```
"gas wanted -1 is negative"
```
However, this error is not bubbled up and the Tx never runs on `DeliverMode`. 
For more details, check the related issue's comments.
______
______
For admin use:

fix(ante): fix reCheckTx gas wanted

---

README.md
x/evm/spec/02_state.md
x/evm/spec/06_hooks.md

This PR replaces the remaining links pointing to evmos.dev with up-to-date links to docs.evmos.org

fix (docs): replace evmos.dev links with docs.evmos.org links

---

x/evm/keeper/benchmark_test.go
x/evm/keeper/keeper_test.go
x/evm/keeper/state_transition_benchmark_test.go
x/evm/keeper/statedb_benchmark_test.go

Closes: #XXX
pass `testing.B` when set up test to avoid nil pointer error when run `go test -bench ^BenchmarkMessageCall$ github.com/evmos/ethermint/x/evm/keeper`
______
______
For admin use:

fix(tests): avoid error when run benchmark

---

CHANGELOG.md
go.mod
go.sum
gomod2nix.toml

This PR removes the replace statement in go.mod that fixed the ics23 version to v0.8.0.
Closes: #1581
______
______
For admin use:

use ics23 v0.9.0

---

rpc/backend/backend_suite_test.go
rpc/backend/call_tx_test.go
rpc/backend/chain_info_test.go
rpc/backend/client_test.go
rpc/backend/evm_query_client_test.go
rpc/backend/filters_test.go
rpc/backend/node_info_test.go
rpc/backend/sign_tx_test.go
rpc/backend/tracing_test.go
rpc/backend/tx_info_test.go
tools/tools.go

This PR executes `gofumpt` for all files, that are not automatically generated.
Additionally, it fixes the comment in `tools/tools.go`, [that was broken](https://github.com/evmos/ethermint/pull/1558/files#diff-e653d1150bfff4aea5ecd6936da16287f53de5d6613833c5bf6ccb4964e2bce4) in the automated addition of the license information to all Go files in #1558.

chore: run gofumpt for non-generated files & fix tools/tools.go

---

CHANGELOG.md

- changelog: added rc-1 changelog entry
- fix: typo fix rc1
Closes: #XXX
______
______
For admin use:

release: v0.21.0-rc1 changelog

---

CHANGELOG.md
go.mod
gomod2nix.toml
scripts/contract-test.sh
scripts/ethermint-devnet.yaml
scripts/integration-test-all.sh
scripts/start.sh
server/config/config.go
tests/integration_tests/configs/default.jsonnet
testutil/network/network.go

Closes: #1612
______
______
For admin use:

fix(rpc): bind default json-rpc listen address to localhost

---

x/evm/migrations/v4/migrate.go
x/evm/migrations/v4/migrate_test.go
x/evm/migrations/v4/types/evm.pb.go
x/evm/migrations/v5/migrate.go
x/evm/types/params.go

Closes: #XXX
______
______
For admin use:

fix(evm): revert v4 migration changes

---

CHANGELOG.md
rpc/backend/account_info_test.go
rpc/types/query_client.go
tests/integration_tests/hardhat/contracts/StateContract.sol
tests/integration_tests/test_storage_proof.py
tests/integration_tests/utils.py

Closes: #XXX
`eth_getProof` reflect the change on block + 1 instead of block:
Contract deployed on Goerli block [0x7dde86](https://goerli.etherscan.io/tx/0x32dccf90fff0d44519d8f88372c2299af475f63d368686a530f39a1419abcde9) 
```
curl --location --request POST $GOERLI_URL\
--header 'Content-Type: application/json' \
--data-raw '{
"jsonrpc": "2.0",
"method": "eth_getProof",
"params": [
"0x0f9fa59eeaed7bc0d0b320927b513c0570a0eed5",
[
"0x0",
"0x1"
],
"0x7dde86"
],
"id": 0
}'
```
Value of storage key `0x0` is `0xc05a754131288197f958cf36c6c807faf5ec12d6`
Contract deployed on Cronos block [0x6c0f35](https://cronos.org/explorer/testnet3/tx/0x884c69dd7a3bd0e74f754b14fa25bfa49398eee9ceb115c80a560ff94e2498a9)
```
curl --location --request POST 'https://evm-t3.cronos.org' \
--header 'Content-Type: …
```

fix(rpc): align block number input behaviour for eth_getProof

---

client/testnet.go

Closes: #1579 
changes the output directory of testnet name to be `ethermintd` instead of `evmosd`.
______
______
For admin use:

fix: use correct naming for testnet output directory

---

Makefile

The `make docker-build` command did not properly work because it was using shell variables that were not defined in the Makefile. These missing variables are added in this PR.

fix (ci): fix docker-build command

---

x/feemarket/spec/01_concepts.md

Closes: #XXX
remove duplicate paragraph in the doc feemarket concepts.
______
______
For admin use:

fix (docs): remove duplicate paragraph in the doc feemarket concepts
