- .github/CODEOWNERS
Closes: #XXX
______
______
For admin use:
> repo: update collaborators

- Makefile
- app/app.go
Closes: #31 
______
______
For admin use:
> makefile: fix `make`

- Makefile
- scripts/contract-test.sh
- scripts/integration-test-all.sh
- scripts/start.sh
- tests/solidity/init-test-node.sh
Closes: #44
Fix script to be able run properly. Most of the script are outdated and uses command tag that does not exists anymore
______
______
For admin use:
> fix script

- docker-compose.yml
- networks/local/ethermintnode/Dockerfile
- scripts/start-docker.sh
Fix the docker-compose and the ability to start a local testnet with make
______
______
For admin use:
> fix docker compose

- app/app.go
- client/testnet.go
- tests/rpc/rpc_test.go
- x/evm/keeper/abci.go
Closes: #48 
______
______
For admin use:
> evm: fix endblock panic

- CHANGELOG.md
- app/app.go
- tests/importer/importer_test.go
- x/evm/keeper/abci.go
- x/evm/keeper/keeper.go
- x/evm/keeper/state_transition.go
- x/evm/types/interfaces.go
> evm: replace block hash storage

- ethereum/rpc/backend.go
- ethereum/rpc/types/utils.go
> rpc: fix eth_getBlockByNumber

- crypto/hd/algorithm.go
Closes: #107
```
crypto/hd/algorithm.go:79:18: key.Child undefined (type *hdkeychain.ExtendedKey has no field or method Child)
make: *** [build] Error 2
```
`Child` method is renamed to `Derive`
______
______
For admin use:
> fix rename method Child of ExtendedKey

- cmd/ethermintd/root.go
fixes: #113
______
______
For admin use:
> remove duplicated vesting tx cli

- go.mod
- go.sum
- x/evm/keeper/keeper.go
- x/evm/keeper/msg_server.go
- x/evm/keeper/state_transition.go
- x/evm/types/errors.go
> evm: stacktrace errors for keeper

- x/evm/types/msg.go
- x/evm/types/msg_test.go
- x/evm/types/tx_data.go
Closes: #XXX
Amount can be nil or zero (for example for simulation or contract deploiement).
Currently if amount is nul, it fails with exception
______
______
For admin use:
> amount can be nil or zero

- app/ante/eth.go
- ethereum/rpc/eth_api.go
- tests/rpc/rpc_test.go
- types/block.go
- x/evm/keeper/state_transition.go
- x/evm/types/protocol.go
> ante, evm: fix panic when checking BlockGasMeter

- docs/architecture/adr-001-state.md
- x/evm/keeper/state_transition.go
> docs: update ADR-001

- app/ante/ante.go
- app/ante/eth.go
> ante: add stacktrace

- x/evm/keeper/abci.go
Closes: #127
set the chainid in the context
______
______
For admin use:
> set chainId in context

- cmd/ethermintd/start.go
Closes: #133 
______
______
For admin use:
> include go-ethereum's log to stdout

- app/ante/ante.go
- app/ante/ante_test.go
- app/ante/utils_test.go
fixes #149
______
______
For admin use:
> add ValidateMemoDecorator to ante handler of evm tx

- ethereum/rpc/eth_api.go
fixes #151
______
______
For admin use:
> fix condition to fill default nonce

- ethereum/rpc/eth_api.go
Closes: #115
Easy quick fix to be more consistent with the value returned by eth_gasPrice (which can be useful for web3 tool to evaluate the value to set)
However the minimum value of gasPrice accepted is never checked ( related to issue #136) Some design discussion is eeded
______
______
For admin use:
> fix gas price value

- ethereum/rpc/eth_api.go
- use sync broadcast
- convert error response to error return
Closes: #158
______
______
For admin use:
> SendTransaction returns error message for invalid tx

- ethereum/rpc/eth_api.go
Closes #160
______
______
For admin use:
> `SendTransaction` wrap `MsgEthereumTx` in cosmos tx

- ethereum/rpc/eth_api.go
Closes #162
______
______
For admin use:
> `GetTransaction` rpc api extract msg from cosmos tx

- .golangci.yml
- app/app.go
- cmd/ethermintd/flags.go
- ethereum/rpc/namespaces/eth/api.go
- ethereum/rpc/namespaces/eth/filters/api.go
- ethereum/rpc/namespaces/eth/filters/filters.go
- x/evm/module.go
- x/evm/types/chain_config.go
Closes: #XXX
Fix linters issue to make pass the CI Job
SA1019 that prevent to use deprecated package (codec.LegacyAmino) has been removed. Not sure if we should rather update the package instead?
______
______
For admin use:
> fix linter issues

- app/ante/eth.go
- app/ante/eth_test.go
Because it set the `From` field which is relied by other handlers
Closes #185
______
______
For admin use:
> Don't skip EthSigVerificationDecorator for recheck tx

- app/app.go
- x/evm/keeper/keeper.go
- x/evm/keeper/keeper_test.go
- x/evm/keeper/statedb.go
- x/evm/keeper/statedb_test.go
Closes #187
Verified in external integration test.
______
______
For admin use:
> fix `AddLog` unmarshaling tx

- ethereum/rpc/types/utils.go
Solution: fix extraData to correct hex decimal
fixes #69
> rpc: fix JSON-RPC block extraData

- types/validation.go
- x/evm/keeper/grpc_query_test.go
- x/evm/types/msg_test.go
Closes: #190 
Removes zero address validation since it is discussed in the issue how this is a valid address in Ethereum.
Updates the tests accordingly.
______
______
For admin use:
> fix: Remove Zero Address validation

- x/evm/keeper/abci.go
- x/evm/keeper/keeper.go
- x/evm/keeper/state_transition.go
- x/evm/keeper/statedb.go
Closes: #139
Verified in external integration tests.
~~Depend on PR #192, since without that, the logs and bloom filter are always empty.~~
______
______
For admin use:
> update block bloom properly

- ethereum/rpc/types/utils.go
Closes: #221
Returns proper 0 address format for parent hash on coinbase block. Small change
______
______
For admin use:
> fix: fix parent hash format

- Makefile
Closes: #199 
Make build the default target when no argument provided to make
______
______
For admin use:
> build: make build the default target when no argument provided

- ethereum/rpc/namespaces/eth/api.go
Closes #240
passes local python script test:
```
w3 = web3.Web3(web3.providers.HTTPProvider("http://localhost:1317"))
addr = w3.geth.personal.importRawKey(VALIDATOR_PRIV_KEY, "1")
nonce1 = w3.eth.get_transaction_count(addr)
tx = w3.eth.send_transaction({"from": addr, "to": COMMUNITY, "value": 1000})
receipt = waittx(w3, tx)
assert w3.eth.get_transaction_count(addr) == nonce1 + 1, 'invalid nonce'
assert w3.eth.get_transaction_count(addr, receipt.blockNumber - 1) == nonce1, 'invalid historical nonce'
```
______
______
For admin use:
> `GetTransactionCount` support query historical state

- ethereum/rpc/backend/backend.go
- ethereum/rpc/namespaces/eth/api.go
Closes #242
Also simplified rpc query with `rpctypes.ContextWithHeight`.
It passes the python script test:
```
w3 = web3.Web3(web3.providers.HTTPProvider("http://localhost:1317"))
addr = w3.geth.personal.importRawKey(VALIDATOR_PRIV_KEY, "1")
nonce1 = w3.eth.get_transaction_count(addr)
tx = w3.eth.send_transaction({"from": addr, "to": COMMUNITY, "value": 1000})
assert w3.eth.get_transaction_count(addr) == nonce1
assert w3.eth.get_transaction_count(addr, "pending") == nonce1 + 1, 'invalid pending nonce'
receipt = waittx(w3, tx)
assert w3.eth.get_transaction_count(addr) == nonce1 + 1, 'invalid nonce'
```
______
______
For admin use:
> implement pending nonce with UnconfirmedTx

- x/evm/keeper/grpc_query.go
- x/evm/keeper/grpc_query_test.go
- x/evm/keeper/keeper.go
> evm: fix `BlockBloom` not found for latest height

- cmd/ethermintd/flags.go
Solution: remove un-used flags
> Problem: redundant log option (fix #289)

- cmd/ethermintd/config/config.go
- cmd/ethermintd/root.go
- go.mod
- go.sum
- server/evmrpc.go
- server/start.go
Closes #340
- add grpc web and rosetta server
- add tx/tm services
- add standalone mode
- update cosmos-sdk to 0.43.0-rc2, which fixed a bug in service startup
- add EnableUnsafeCORS option to evm rpc server
______
______
For admin use:
> sync start command with cosmos-sdk 0.43

- init.bat
> Problem: missing support of init.sh for windows #339

- init.sh
Closes: #267 
checking if `jq` is installed before moving forward when running `init.sh`
______
______
For admin use:
> build: check if jq installed in init.sh

- x/evm/keeper/grpc_query.go
- x/evm/keeper/grpc_query_test.go
> fix get storage

- docs/basics/json_rpc.md
- server/config/config.go
Closes: #388 
Adds Net and Web3 namespaces as default.
______
______
For admin use:
> fix: Set Eth, Web3 and Net namespaces as default

- ethereum/rpc/namespaces/miner/api.go
Closes: #173 
Increase fee adjustment on the `miner_setEtherbase` message to prevent some failing transactions.
______
______
For admin use:
> fix setEtherbase fee

- init.bat
> Problem: incorrect comment of init.bat (fix #397)

- docs/basics/gas.md
Closes: #90
The original document was overall well written. I just completed with additional information
______
______
For admin use:
> update gas consumption document

- docs/guides/wallets/metamask.md
Closes: #XXX
Frequently asked question, needs probably to be mentioned in the doc
______
______
For admin use:
> Update metamask docs chainId

- app/app.go
keep the scaffolding up-to-date:
https://github.com/cosmos/cosmos-sdk/blob/release/v0.43.x/simapp/app.go#L433
______
______
For admin use:
> Call SetModuleVersionMap in InitChainer

- README.md
- docs/.vuepress/config.js
- docs/DOCS_README.md
- docs/api/README.md
- docs/api/json-rpc/endpoints.md
- docs/api/json-rpc/events.md
- docs/api/json-rpc/namespaces.md
- docs/api/json-rpc/running_server.md
- docs/basics/tokens.md
- docs/guides/README.md
- docs/guides/keys-wallets/keyring.md
- docs/guides/keys-wallets/metamask.md
- docs/intro/clients.md
- docs/intro/resources.md
- docs/quickstart/run_node.md
- docs/testnet/README.md
- docs/testnet/cloud_providers.md
- docs/testnet/join.md
- docs/testnet/testnet.md
- x/evm/atlas/atlas-v0.3.1.md
Closes: #XXX
______
______
For admin use:
> docs: additional content

- x/evm/keeper/state_transition.go
> evm: fix params

- docs/api/json-rpc/endpoints.md
Closes: #XXX
Fix rpc examples
______
______
For admin use:
> fix examples

- app/ante/eth.go
- x/evm/keeper/grpc_query.go
- x/evm/keeper/state_transition.go
Decouple tracer initiation from the `NewEVM` function to unblock `traceTransaction` endpoint development. 
______
______
For admin use:
> Decouple tracer from evm creation

- CHANGELOG.md
- client/debug/debug.go
- cmd/ethermintd/root.go
- docs/basics/accounts.md
> client: add EIP55 address to `debug` command

- docs/DOCS_README.md
- docs/guides/README.md
- docs/guides/validators/faq.md
- docs/guides/validators/overview.md
- docs/guides/validators/setup.md
Closes: #XXX
This PR corrects some language in the Validator guide and ensures consistency of language and style across it.
______
______
For admin use:
> Docs: Corrections for Validator Guide

- init.sh
Closes: #XXX
______
______
For admin use:
> add shebang to init.sh

- x/evm/types/genesis.go
- x/evm/types/genesis_test.go
Solution: in GenesisAccount, make empty Code legitimate
fixes: #510
> Problem: export state & import as genesis (fix #510)

- x/evm/keeper/state_transition.go
fix performance from https://dashboard.github.orijtech.com/benchmark/f76839269598458a83fa489139899ad0
> evm: conditional hook snapshot

- ethereum/rpc/backend/backend.go
Closes: #235 
Update BlockByNumber and BlockByHash to use gasUsed rather than gasLimit for correct value
______
______
For admin use:
> Return correct gas used amount in BlockByNumber and BlockByHash

- x/evm/keeper/utils.go
- x/evm/keeper/utils_test.go
> evm: check tx cost not negative

- go.mod
- go.sum
Closes: #581
Solution:
- replace iavl dependency to v0.17.1
______
______
For admin use:
> Problem: node crash in concurrent query

- app/ante/eth.go
Closes: #551 
For error messages in app/ante/eth.go, use (*T)(nil) instead of &T{} to avoid unnecessary memory allocation.
______
______
For admin use:
> fix：convert &T{} to (*T)(nil) in error message to avoid unnecessary memory allocation

- .github/CODEOWNERS
- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> docs: v0.6.0 changelog

- .github/CODEOWNERS
- CHANGELOG.md
* docs: v0.6.0 changelog
* update codeowners
Closes: #XXX
______
______
For admin use:
> docs: v0.6.0 changelog (#605)

- docs/architecture/PROCESS.md
- docs/architecture/adr-002-evm-hooks.md
Contains fixes for broken links in markdown files and fixes the [markdown-link-check](https://github.com/tharsis/ethermint/runs/3809842927?check_suite_focus=true) action
______
______
For admin use:
> docs: fix broken links in markdown files

- Makefile
- proto/ethermint/evm/v1/tx.proto
Was breaking `make proto-gen`
Closes: #XXX
______
______
For admin use:
> fix: proto-gen broken env var

- app/ante/eth.go
- app/ante/eth_test.go
The `PrepareAccessList` call is moved into `ApplyMessage` earlier, this PR is just to cleanup the dead code.
______
______
For admin use:
> Remove unused AccessListDecorator

- CHANGELOG.md
- LICENSE
closes: #796 
Ref: https://choosealicense.com/licenses/lgpl-3.0/#
> docs: re-license to LGPLv3

- CHANGELOG.md
- release: `v0.8.0` changelog (#757)
- release: v0.8.1 changes (#775)
- changelog `v0.8.1` (#805)
- changelog
> release: changelog `v0.9.0`

- .mergify.yml
- CHANGELOG.md
- release: changelog `v0.9.0` (#806)
- docs: backport changelog updates
> docs: backport changelog updates

- x/evm/types/tracer_test.go
> fix broken tracer unit test

- CHANGELOG.md
- app/ante/eth.go
- app/ante/eth_test.go
- app/ante/handler_options.go
- rpc/ethereum/backend/backend.go
- rpc/ethereum/namespaces/eth/api.go
- x/evm/keeper/utils.go
- x/evm/types/msg.go
Closes: #915
Solution:
- Don't check min-gas-price for evm tx in london hardfork
______
______
For admin use:
> fix: minimal-gas-prices and baseFeePerGas conflicts

- x/evm/spec/08_params.md
`CatalystBlock` don't exists anymore.
Closes: #XXX
______
______
For admin use:
> remove unused parameters from evm spec

- CHANGELOG.md
- release: v0.10.0-alpha changelog (#891)
- release: v0.10.0-alpha2 (#923)
- release: v0.10.0-beta1 changelog (#941)
- release: v0.10.0 final (#959)
- release: v0.10.1 changelog (#971)
- release: changelog (#972)
- changelog (#973)
> docs: changelog fix

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> release: v0.11.0 changelog

- server/flags/flags.go
- server/start.go
Closes: #XXX
Add the possibility to enable unsafe cors from a flag
______
______
For admin use:
> add enable unsafe cors flag

- app/ante/eth.go
- app/ante/eth_test.go
The MaxTxGasWanted is not used anymore
______
______
For admin use:
> cleanup an unused const

- CHANGELOG.md
- x/evm/types/storage.go
- x/evm/types/storage_test.go
- evm: update empty hash check for storage state (#1016)
- v0.12.1: changelog
Closes: #XXX
______
______
For admin use:
> changelog: v0.12.1

- CHANGELOG.md
- x/feemarket/migrations/v010/migrate_test.go
- x/feemarket/migrations/v09/types/feemarket.pb.go
- x/feemarket/migrations/v09/types/genesis.pb.go
- release: v0.12.0 changelog
- changelog: v0.12.1 (#1019)
- changelog: v0.12.2 (#1022)
Closes: #XXX
______
______
For admin use:
> release: v0.13.0

- types/validation.go
- types/validation_test.go
Closes: #XXX
______
______
For admin use:
> Add ValidateNonZeroAddress utility function

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> release: v0.14.0 changelog

- .github/workflows/test.yml
- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> ci: bump simulations timeout

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> release: v0.15.0 changelog

- CHANGELOG.md
> release: merge release branch changes back to main

- CHANGELOG.md
- go.mod
- go.sum
- server/util.go
it's useful in app-hash mismatch situation.
______
______
For admin use:
> Add cli rollback command

- CHANGELOG.md
- app/ante/fee_market.go
- app/ante/fees.go
- app/ante/handler_options.go
Closes: #XXX
______
______
For admin use:
> ante: refactor

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> release: `v0.16.0` changelog

- .github/workflows/proto.yml
- .github/workflows/semgrep.yml
- Makefile
justification from [this](https://github.com/evmos/evmos/pull/705) PR from the evmos repository
- create action in order to remove makefile buf dependency
- fix semgrep deprecation alert
______
______
For admin use:
> fixed buf makefile dependency, update semgrep workflow

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> release: v0.17.2 changelog

- CHANGELOG.md
Closes: #XXX
Add release title and date to Changelog 
______
______
For admin use:
> changelog release date

- ethereum/eip712/eip712.go
Closes: #XXX
______
______
For admin use:
> fix: eip712 support for ethtypes arrays

- CHANGELOG.md
- ethereum/eip712/eip712.go
Minor fixes for eip712.
Support for optional parameters.
Time type
Support for basic types arrays.
______
______
For admin use:
> fixes for 19.0.1 (#1305)

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> Update `v0.19.2` Changelog

- app/ante/fees.go
- app/ante/fees_test.go
Closes: #1225 
Skip checks for transaction fee amount when simulating a transaction. This change will mirror the Cosmos SDK's fee consideration, and more important, allow for easier tx simulations and gas fee estimates.
______
______
For admin use:
> fix: skip fee check on tx simulation

- go.mod
- go.sum
ibc-go v3.3.0
ethermint v0.19.4
______
______
For admin use:
> upgrade to ibc-go v3.3.0

- .gitleaks.toml
- init.sh
Closes: https://linear.app/evmos/issue/ENG-1083/add-gitleaksignore-to-evmos-andand-ethermint
______
______
For admin use:
> fix(ci): add gitleaks config

- init.sh
- tests/solidity/init-test-node.sh
Closes: #XXX
______
______
For admin use:
> Enable metrics on init.sh script

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> Release `v0.20.0` 

- docs/api/proto-docs.md
- docs/architecture/README.md
- docs/architecture/adr-001-state.md
> Fix: typos

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> fix: updated Changelog to include rc-1 release

- x/evm/spec/08_params.md
Closes: #XXX
Added new hardfork rows after london at [08_params.md](https://github.com/evmos/ethermint/blob/main/x/evm/spec/08_params.md).
______
______
For admin use:
> Add new hardfork rows after london

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> imp (changelog): minor improvement to changelog

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> fix (changelog): adjust year to 2023 for v0.21.0-rc2 release

- CHANGELOG.md
Closes: #XXX
______
______
For admin use:
> chore(release) update changelog

- CHANGELOG.md
Closes: https://linear.app/evmos/issue/ENG-1414/release-ethermint-v021-final
______
______
For admin use:
> chore: sync main with v0.21.x branch

- client/keys/add.go
- ethereum/eip712/eip712.go
- rpc/backend/node_info.go
- rpc/namespaces/ethereum/eth/api.go
- rpc/namespaces/ethereum/eth/filters/filters.go
- rpc/namespaces/ethereum/miner/unsupported.go
- rpc/websockets.go
- tests/importer/chain_ctx.go
- x/evm/keeper/abci.go
- x/evm/keeper/config.go
- x/evm/keeper/grpc_query.go
- x/evm/statedb/statedb.go
- x/evm/types/access_list_tx.go
- x/evm/types/legacy_tx.go
- x/evm/types/tracer.go
- x/evm/types/tx_args.go
- x/feemarket/keeper/abci.go
Closes: #XXX
Fix linter issues due to golangcli upgrade
______
______
For admin use:
> fix: lint issues

- CHANGELOG.md
Closes: #XXX
Added missing entries to changelog and fix wrong location on old PR to prepare for new release
______
______
For admin use:
> add missing entries to changelog
